export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const FETCH_ROBOTS_PENDING = 'FETCH_ROBOTS_PENDING';
export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS';
export const FETCH_ROBOTS_FAIL = 'FETCH_ROBOTS_FAIL';
